#!/bin/sh

set -e

PIDFILE="/var/run/pdm.pid"

case "$1" in
  start)
	echo "Starting Pandora Display Manager: pdm"
	/pdm/pdm /pdm/ &
  ;;

  stop)
	echo "Stopping Pandora Display Manager: pdm"
	kill `cat ${PIDFILE}`
	rm ${PIDFILE}
#	dd if=/dev/zero of=/dev/fb0 2>/dev/null || dd if=/dev/zero of=/dev/fb/0 2>/dev/null
  ;;

  *)
        echo "usage: $0 { start | stop }"
  ;;
esac

exit 0
